### PR TITLE
Add new Leclercq-RGIV6 glacier match list

### PR DESCRIPTION
**Pull request by DavidParkes**
This is a pass of all regions (except Antarctica) in the Leclercq et al. 2014 dataset, attempting to identify them with RGIV6 glaciers, with varying levels of success. The added readme file contains a description of the methodology. Note this is not a replacement for or even necessarily an exact match with the existing file matching Leclercq and European RGIV5 glaciers.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks for the nice contribution! 

Did you to any check of the links? E.g. for famous glaciers with names or similar.

I'm asking because false positives are likely as well, and should be acknowledged. The original RGIV5 list was compiled by @jlandmann and if I recall well there was a lot of manual editing going on.

**Comment by jlandmann** [comment]
It's cool to see an update of the links! :-)
But yes, @fmaussion, you are right! If I remember correctly the RGI-Leclercq links were not as prone to false positives than links to other inventories, but I guess a manual cross-check is definitely a good idea.

**Comment by DavidParkes** [comment]
I haven't done a check based on names, but that's certainly a good idea and I'll do this next week. I'll also compared with the RGI5 linkages from the other list; these don't necessarily need to match exactly, but it's still informative if some don't. All of the links made were done by applying the standard I gave manually while looking at the RGI shapefiles, rather than with a script, so in that sense there's only so much a manual cross-check in terms of looking at maps can be valuable (though looking at things a second time never hurts).

I've also got a quick edit to the file to remove one duplicate (an RGI glacier that got selected as a best effort for one Leclercq glacier, but was subsequently positively identified as another) which I'll do once I've done any manual cross-checking. The request should probably not be merged until that's done.

**Comment by fmaussion** [comment]
Let's get this in soon!

**Comment by DavidParkes** [comment]
The one duplicate entry is now fixed. More cross-referencing through various methods is possible, but that's beyond what I'm using it for right now and it is correct enough to commit, I think.

**Comment by fmaussion** [comment]
This is awesome! Sorry for letting this stay for so long -> getting in now

**Pull request merged**
