### PR TITLE
 Update WGMS data to 2021-05 

### PR DESCRIPTION
**Pull request by lilianschuster**
This updates the WGMS direct glaciological mass-balance data to the most recent state (i.e. until end of 2020). 

Some remarks becore accepting the pull request:
- there is no duplicate icelandic glacier anymore  (3110 does not exist anymore, only 3089)
	- just removed the part where the icelandic duplicate is deleted!!!
- I use the same links as before, so **rgi_wgms_links_20200414_manual_addition.csv**
	- I could change this but not sure how you created that link list (I guess another script?). So I just left it the same. 
	- I just checked out where in OGGM this is used and found out that here: https://github.com/OGGM/oggm/blob/master/oggm/utils/_downloads.py#L1787, the csv file without the "manual_addition" which is one day older (https://github.com/lilianschuster/oggm-sample-data/blob/dev/wgms/rgi_wgms_links_20200415.csv) is used. Not so sure which one is better to use, but probably it makes sense to have the same for both? 
	  
- there is no file named: https://cluster.klima.uni-bremen.de/~oggm/rgi/rgi62_allglaciers_stats.h5, there is only a file called: https://cluster.klima.uni-bremen.de/~oggm/rgi/rgi62_stats.h5 
       - so I took that one, I hope that this is fine!

- is that ok to have the notebook and the plots (in wgms/plots/ subfolder) in the wgms github folder, like that it is easier to update it ? The raw data are not inside as they are too large.

### CODE REVIEW

**Comment by fmaussion** [comment]
> Not so sure which one is better to use, but probably it makes sense to have the same for both?

What are the differences between the two?

> there is no file named: https://cluster.klima.uni-bremen.de/~oggm/rgi/rgi62_allglaciers_stats.h5, there is only a file called: https://cluster.klima.uni-bremen.de/~oggm/rgi/rgi62_stats.h5

Yes I think I did that renaming. What's the context?

> is that ok to have the notebook and the plots (in wgms/plots/ subfolder) in the wgms github folder, like that it is easier to update it ? 

Yeah, there is really no real central repository for these kind of things as of now. What comes closest is this here: https://github.com/OGGM/oggm-shop-notebooks (the notebook is already there). Thoughts? At the very least you'll need to crop the output in the notebooks before committing

**Comment by lilianschuster** [comment]
- as discussed, I moved the notebook to oggm-shop-notebooks and added a date into the name (output is removed)
- actually, in the notebook, you load the ..._manual_addition file, then do some link changes because of the RGI and then save it as 20200415 (i.e. the file that is used in OGGM) . So everything was fine, I was just confused. 
- To get some statistics (like cenlon, glacier type, ..) for the rgi_wgms_..._links file, you use the https://cluster.klima.uni-bremen.de/~oggm/rgi/rgi62_stats.h5 file. So, probably it was just a renaming there. 

From my perspective, this can be merged now.

**Comment by fmaussion** [comment]
Sorry - can I ask you one last favor? 
- remove the plots from your PR 
- add the new link file with a new date instead of replacing the old one? 
(sorry thats two ;-)

**Comment by lilianschuster** [comment]
ok, done now (although, to be super-consistent, I should also change the filename then in the oggm-shop-notebooks?!)

**Comment by fmaussion** [comment]
Thanks @lilianschuster !

**Pull request merged**
