### PR TITLE
Adding t* reference lists for VAS model.

### PR DESCRIPTION
**Pull request by oberrauch**
This allows to access the `ref_tstar` lists for the VAS model via `get_demo_file()`.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks a lot! That's great. can you add the `.DS_Store` file to `.gitignore` and update your commit? Thanks!!!!

**Comment by oberrauch** [comment]
Yeah sure, forgot about that...

> Thanks a lot! That's great. can you add the `.DS_Store` file to `.gitignore` and update your commit? Thanks!!!!

**Comment by fmaussion** [comment]
Sorry about the RGI5 files... I think we should start to remove support for RGI5 altogether soon

**Comment by oberrauch** [comment]
> Sorry about the RGI5 files... I think we should start to remove support for RGI5 altogether soon

Especially since the RGI version seems to make no difference in the outcome.

**Comment by oberrauch** [comment]
However, the file names are another issue. At first glance the prefix `vas_` makes perfect sense, but the prefix is omitted in the `cfg.PARAMS`. This would result in the same key (e.g., `ref_tstars_rgi5_cru4`) for both the OGGM and the VAS reference list.

My suggestion would be to rename the file into: `oggm_ref_tstars_vas_rgi5_cru4.csv` which results in the key `ref_tstars_vas_rgi5_cru4`.

What do you think?!

**Comment by oberrauch** [comment]
Another solution would be to keep the prefixes (`oggm_` and `vas_`) as keys. Even tough this would probably result in a lot of changes throughout the codebase...

**Comment by fmaussion** [comment]
> My suggestion would be to rename the file into: oggm_ref_tstars_vas_rgi5_cru4.csv which results in the key ref_tstars_vas_rgi5_cru4.

This looks good to me! Of course I didn't think about alternative files when I created those files in the first place.

**Comment by oberrauch** [comment]
If we are planning to add even more reference lists for alternative model, I would favour to keep the prefixes. If it's only the VAS files I'm fine with the other solution...

**Comment by fmaussion** [comment]
I can't really decide now, because I don't remember all the details. Can this PR wait until I review your code?

**Comment by oberrauch** [comment]
Yes, it can. So far the `ref_tstars` are stored in the data directory.

**Comment by oberrauch** [comment]
Hey @fmaussion, what is the best way to continue with this PR. If I add the prefixes to the reference t* list, I have to change the `cfg.py` file simultaneously. So should I open another PR where I just change the affected lines?! Or should we merge the VAS PR with the changed `cfg.py` file first and then merge this PR?!

**Comment by oberrauch** [comment]
Hi @fmaussion. If you merge this PR, I could finalize the VAS PR.

**Comment by fmaussion** [comment]
> Hi @fmaussion. If you merge this PR, I could finalize the VAS PR.

right, sorry. In the VAS PR you now have to update the sample-data commit hash:

change:

https://github.com/OGGM/oggm/blob/91719ae3cea3dfac2cf6d5a41d764b07b6e7a179/oggm/utils/_downloads.py#L59

to:

```python
SAMPLE_DATA_COMMIT = '4f0b944d58a56b883e80818ac14a7a45414b2e09'
```

**Pull request merged**
