### PR TITLE
change images for new filter

### PR DESCRIPTION
**Pull request by pat-schmitt**
More image changes for the filter. For this, I had to reduce the tolerance quite a bit to 1.

Some figures also changed only due to changes in matplotlib. For these glaciers, I added an additional figure. The other figures I have replaced.

I am not sure what is the best strategy regarding tolerance. Because now it is very small -> very likely that small changes in matplotlib lead to fails. Probably we should change the tolerance afterwards again to something like 3.5, to avoid too much work?

Here an overview of the RMS for the different test figures and I indicated the ones where matplotlib caused the failing:

| Image                      | RMS  |            |
|----------------------------|------|------------|
| test_plot_region_model     | 3.8  |            |
| test_coxe                  | 3.55 |            |
| test_catch_areas           | 3.2  | matplotlib label |
| test_modelsection_withtrib | 4.74 |            |
| test_modelsection          | 5.54 |            |
| test_multiple_inversion    | 3.25 |            |
| test_downstream            | 3.2  | matplotlib label |
| test_centerlines           | 3.2  | matplotlib label |
| test_domain                | 3.2  | matplotlib label |
| test_chhota_shigri         | 1.33 |            |
| test_multiple_models       | 1.84 |            |
| test_modeloutput_map       | 1.01 |            |
| test_inversion             | 1.01 |            |
| test_flowlines             | 1.76 |            |
| test_plot_region_inversion | 1.57 |            |

### CODE REVIEW

**Comment by fmaussion** [comment]
> Probably we should change the tolerance afterwards again to something like 3.5, to avoid too much work?

Yes sounds good! Thanks

**Comment by pat-schmitt** [comment]
Could I merge?

**Comment by fmaussion** [comment]
> Could I merge?

Yes - if you trust you understand the need for more than one image or replace an image that's good for me! Otherwise we can have a brief chat. I can't be sure that it is always a good idea to add an image or replace all images with a single new one

**Comment by pat-schmitt** [comment]
I thought if I add an additonal image for an 'matplotlib-error' I add more possibilities to compare to. So if oneday some small changes in matplotlib labels are undone again, we already have the old version to compare to.

And I replaced the images where really something in oggm has changed (in this case the bed height at the terminus). So if we oneday undo this changes I think it is also a good idea to actively change the figures again.

**Comment by fmaussion** [comment]
> I thought if I add an additonal image for an 'matplotlib-error' I add more possibilities to compare to. So if oneday some small changes in matplotlib labels are undone again, we already have the old version to compare to.

Yes exactly. What's important is that the content (i.e. the OGGM related part) doesn't change between the plot. Perfect!

**Comment by pat-schmitt** [comment]
I just checked all images one more time and in one image (test_flowlines) the position head of the main flowline has changed and I am not sure if this is matplotlib or oggm related. However, I think it has nothing to do with the changes in the filter.

old:
test_flowlines_2

new: 
test_flowlines_3

**Comment by fmaussion** [comment]
Yes just take the new one - no worries

**Pull request merged**
